# shape: sequence_diagram

# 사용자; db; server;

사용자: {
  icon: https://icons.terrastruct.com/essentials%2F005-programmer.svg
  shape: image
}
db: {
  icon: https://icons.terrastruct.com/aws%2FDatabase%2FAmazon-RDS_MariaDB_instance-alt_light-bg.svg
  shape: image
}
server: {
  icon: https://icons.terrastruct.com/essentials%2F112-server.svg
  shape: image
}
load_balancer: {
  icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20Load%20Balancing.svg
  shape: image
}
storage: {
  icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FStorage%2FCloud%20Storage.svg
  shape: image
}

sqs: {
  icon: https://icons.terrastruct.com/aws%2FApplication%20Integration%2FAmazon-Simple-Queue-Service-SQS_Message_light-bg.svg
  shape: image
}

codes: {
  icon: https://icons.terrastruct.com/essentials%2F006-window.svg
  shape: image
}

docker: {
  icon: https://icons.terrastruct.com/dev%2Fdocker.svg
  shape: image
}

windows: {
  icon: https://icons.terrastruct.com/dev%2Fwindows.svg
  shape: image
}

mac : {
    icon: https://icons.terrastruct.com/dev%2Fapple.svg
    shape: image
  }
  
data : {
    icon: https://icons.terrastruct.com/infra%2F012-data.svg
    shape: image
  }
