direction: down

추진체계: {
  style: {
    fill: "#eeeeee"
    font-size: 30
  }

  a1: 프로젝트 계획 수립 {
    width: 400
    style.font-size: 30
  }

  saas: Saas 플랫폼 개발 {
    width: 400
    style: {
      font-size: 30
    }
    explanation: |md
        - 플랫폼 설계, 백엔드 설계, 프론트엔드 설계
      |
  }
  a1 -> saas

  git: Git 연동 개발 {
    width: 400
    style: {
      font-size: 30
    }
    explanation: |md
        - Git 폴더 관리, Git 개별 Code 관리
      |
  }
  saas-> git
  
  template: 사용자용 템플릿 엔진 개발 {
    width: 400
    style: {
      font-size: 30
    }
    explanation: |md
        - 도커 템플릿 생성 모듈
        - DB 템플릿 생성 모듈, DB API 템플릿 생성 모듈
        - Dashboard 템플릿 생성 모듈,  RTU 템플릿 생성 모듈
      |
  }
  saas -> template

  opensw: 오픈소스 모니터링 {
    width: 400
    style: {
      font-size: 30
    }
    explanation: |md
        - 다운로드 횟수, 모델참조 횟수
      |
  }
  saas -> opensw
  template -> git
  template -> opensw

  community: 오픈소스 커뮤니티 활성화 {
    width: 400
    style: {
      font-size: 30
    }
    explanation: |md
        - 소스 코드 공개, 이슈 트래킹, 문서화
      |
  }
  git -> community
  opensw -> community
  
}
